spring:
  application:
    name: xianyu-demo
  profiles:
    active: @activatedProperties@
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  lifecycle:
    timeout-per-shutdown-phase: 30s
  main:
    #不允许循环依赖，先google解决，如果是业务循环依赖，看看中间是否能加一层，如果循环依赖了@SpyBean会报错
    allow-circular-references: false
    lazy-initialization: false
    allow-bean-definition-overriding: false
    banner-mode: off
  docker:
    compose:
      enabled: false
server:
  port: 8090
logging:
  config: classpath:logback.xml
redisson:
  host: ${spring.data.redis.host}
  port: ${spring.data.redis.port}
  netty-threads: 1
  threads: 1
  connection-minimum-idle-size: 1
  connection-pool-size: 1
domain:
  event:
    sender:
      type: event-bus
management:
  endpoints:
    web:
      exposure:
        include: health,info,modulith
  endpoint:
    modulith:
      enabled: true
