spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/xianyu-demo?currentSchema=public
    username: postgres
    password: Abc123456
  data:
    redis:
      host: localhost
      port: 6379
cache:
  caffeine:
    maximumSize: 1000
    expireAfterWriteSeconds: 300
  redis:
    timeToLiveSeconds: 600
logging:
  level:
    org.springframework.boot.docker.compose: trace
