spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/postgres?currentSchema=xianyu-demo
    username: postgres
    password: 123456
  data:
    redis:
      host: localhost
      port: 16379
  # 如果连接测试库，可以移回测试目录的配置文件
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
      schema-locations: classpath:sql/schema.sql
  docker:
    compose:
      file: classpath:compose.yaml
      enabled: true
cache:
  caffeine:
    maximumSize: 1000
    expireAfterWriteSeconds: 300
  redis:
    timeToLiveSeconds: 600
logging:
  level:
    org.springframework.boot.docker.compose: trace
